### PR TITLE
fix atom v1.13.0 deprecation issues

### PR DESCRIPTION
**Pull request by UziTech**

### CODE REVIEW

**Comment by jakesankey** [comment]
build failed

**Comment by 1ukaz** [comment]
Is this going to be merged? What it takes or what is failing that you won't merge it?

**Comment by jakesankey** [comment]
This branch has merge conflicts. It just needs to be merged with master, resolve conflicts, and push again. Then I can merge.

**Comment by 1ukaz** [comment]
Sounds fair. I will check if I can find myself a time window this week to
have a look at this and maybe I could contribute a little bit. Not sure
about the precedence of the conflicts, but I'll try it out.

**Comment by 1ukaz** [comment]
I don't understand @jakesankey ... Here it says that there is no conflicts at all and this is ready to merge. Will you?

**Comment by jakesankey** [comment]
Interesting. It showed that it was conflicting earlier today. I'll get a new tag published in a bit. To your question on why it wasn't included. I generally cut releases of single fixes or enhancements that way it is easy to roll back just the one thing if needed.

**Pull request merged**
