### PR TITLE
Replace directory separator for repo directory on Windows

### PR DESCRIPTION
**Pull request by thinkh**
Fix for #7 

Please test on other OS too.

### CODE REVIEW

**Comment by mmcintyre123** [comment]
Tested in Windows, and the "revert" feature sort of works now for txt files, but it also adds a new line which has to separately be reverted.  However, the "copy" feature is not working, and it doesn't work properly at all in .rb, .feature (cucumber), or .js files.  Perhaps the / and \ need to be changed in other places as well?

**Comment by jakesankey** [comment]
Good news and bad news..  Good news: thanks for looking into this and locating the area that is causing the issue! 

Bad news: Now it doesn't work on Mac :) Now Mac gets the same issue the Windows version was having.

**Comment by mmcintyre123** [comment]
Hey all, I don't code, but I did find these helpful sites.  Could someone take a look?  Hope this helps!
Thanks!

http://stackoverflow.com/questions/15364823/node-js-for-windows-and-macs-forwardslash-backslash-rectification
http://stackoverflow.com/questions/2417485/file-separator-vs-slash-in-paths
http://shapeshed.com/writing-cross-platform-node/
https://gist.github.com/domenic/2790533
http://dailyjs.com/2012/05/23/windows-and-node-4/

**Comment by MattiJarvinen** [comment]
Ok so the fix for path separator should be OS dependant

```process.platform is 'win32'```

Example:

https://github.com/atom/atom/blob/2893772d1a5df8b6ea394e14ebb8eab637cb731b/build/tasks/install-task.coffee

**Comment by jakesankey** [comment]
Thanks @MattiJarvinen and everyone else. I published a new version today. Try it out and let me know if you still have issues.

**Comment by yeluoqiuzhi** [comment]
I was on osx now, I have installed the newest version, but It still threw the same error.

**Pull request closed without merging**
