### PR TITLE
Moved buttons to top left corners, changed styling a bit

### PR DESCRIPTION
**Pull request by chamini2**
Moved buttons to top left corners, now the position doesn't depend on diff size.

Changed styling to use icons included in Atom with descriptive title (mouse hover).

screen shot 2016-05-06 at 2 30 28 am

### CODE REVIEW

**Comment by chamini2** [comment]
Or we could go for the traditional red for `X`:

screen shot 2016-05-06 at 2 34 29 am

Maybe even follow OS X's color palette:

screen shot 2016-05-06 at 2 33 57 am

**Comment by chamini2** [comment]
This PR closes #8

**Comment by chamini2** [comment]
Copying generates a `success` notification, maybe show the copy button green too or change the notification to `info` blue.

**Comment by jakesankey** [comment]
Thanks a lot! Published 1.3.0 just now.

**Pull request merged**
