### PR TITLE
fixed Windows diff modal open

### PR DESCRIPTION
**Pull request by aljinovic**
fix for "Uncaught TypeError: Cannot read property 'length' of null"

### CODE REVIEW

**Comment by marcusorjames** [comment]
Can confirm fixed :)

**Comment by jakesankey** [comment]
Thanks, I will check it out on Mac to confirm cross-platform support.

**Comment by chamini2** [comment]
I'm running OS X and it doesn't throw any `TypeError`

**Comment by jakesankey** [comment]
Thanks! Published 1.3.1

**Pull request merged**
